name: Service IP CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'app/service-ip/**'
      - 'app/package.json'
      - 'app/package-lock.json'
      - '.github/workflows/service-ip-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'app/service-ip/**'
      - 'app/package.json'
      - 'app/package-lock.json'
      - '.github/workflows/service-ip-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/service-ip

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json

    - name: Install dependencies
      run: |
        cd ..
        npm ci
        cd service-ip

    - name: Run type check
      run: npx tsc --noEmit

    - name: Run tests
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: app/service-ip

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json

    - name: Install dependencies
      run: |
        cd ..
        npm ci
        cd service-ip

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: service-ip-build
        path: app/service-ip/dist/